// Generated by CoffeeScript 1.8.0
(function() {
  var RandomRobot, addModify, calculate, callback, callback4, color, disable, enable, k, modifyLabel, newList, reset, robot, setBubbleEnable, setLabel;

  k = $("#control-ring li");

  reset = function() {
    return 0;
  };

  modifyLabel = function(unread, data) {
    unread.innerHTML = data;
    return 0;
  };

  enable = function() {
    var li, liList, _i, _len;
    liList = $("#control-ring li");
    for (_i = 0, _len = liList.length; _i < _len; _i++) {
      li = liList[_i];
      if (!$(li).find("[class=unread]").get(0)) {
        color("rgba(61,40,166,1)", li);
      }
    }
    $("#control-ring").click(addModify);
    return 0;
  };

  calculate = function() {
    var add, span, sum, _i, _len, _ref;
    sum = 0;
    add = function(span) {
      return sum = sum + parseInt(span.innerHTML);
    };
    _ref = $("[class=unread] span");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      span = _ref[_i];
      add(span);
    }
    $("#cal-result").get(0).innerHTML = sum;
    $(".info").css("background-color", "grey");
    return $("#info-bar").unbind("click");
  };

  setBubbleEnable = function() {
    color("rgba(61,40,166,1)", ".info");
    return $("#info-bar").click(calculate);
  };

  callback = function(data, textStatus) {
    var UnreadList, unread, _i, _len;
    UnreadList = $("[class=unread] span");
    for (_i = 0, _len = UnreadList.length; _i < _len; _i++) {
      unread = UnreadList[_i];
      if (unread.innerHTML === "...") {
        modifyLabel(unread, data);
      }
    }
    enable();
    if ($("li [class=unread]").length === 5) {
      setBubbleEnable();
      $("#control-ring").unbind("click");
    }
    return 0;
  };

  callback4 = function(data) {
    var UnreadList, unread, _i, _len;
    UnreadList = $("[class=unread] span");
    for (_i = 0, _len = UnreadList.length; _i < _len; _i++) {
      unread = UnreadList[_i];
      if (!(unread.innerHTML === "...")) {
        continue;
      }
      modifyLabel(unread, data);
      break;
    }
    enable();
    if ($("li [class=unread]").length === 5) {
      calculate();
    } else {
      robot($("li [class=unread]").length);
    }
    return 0;
  };

  color = function(colorName, li) {
    return $(li).css("background-color", "" + colorName);
  };

  disable = function() {
    var li, liList, _i, _len;
    liList = $("#control-ring li");
    for (_i = 0, _len = liList.length; _i < _len; _i++) {
      li = liList[_i];
      color("grey", li);
    }
    $("#control-ring").unbind("click");
    return 0;
  };

  addModify = function(e) {
    var tar;
    tar = e.target || window.target;
    if (!$(tar).find("span").get(0)) {
      tar = tar.parentNode;
    }
    if (!$(tar).find("[class=unread]").get(0)) {
      setLabel(tar);
      $.get("/", callback);
      return disable();
    }
  };

  setLabel = function(tar) {
    var unread;
    unread = $("<div class='unread'><span>...</span></div>");
    $(tar).append(unread.get(0));
    return 0;
  };

  newList = [];

  robot = function(seq) {
    var curIndex, tar;
    if (seq > 4) {
      return 0;
    }
    curIndex = newList[seq];
    tar = $("#control-ring li").get(curIndex);
    setLabel(tar);
    $.get("/", callback4);
    return disable();
  };

  RandomRobot = function() {
    var cur, curSeq, item, numList, str, _i, _len;
    numList = ["A", "B", "C", "D", "E"];
    str = "";
    while (newList.length < 5) {
      cur = Math.floor(Math.random() * 5);
      k = true;
      for (_i = 0, _len = newList.length; _i < _len; _i++) {
        item = newList[_i];
        if (item === cur) {
          k = false;
        }
      }
      if (k) {
        newList.push(cur);
        str += numList[cur];
      }
    }
    curSeq = $("<span id='seqNum'>" + str + "</span>");
    $(".info").append(curSeq);
    return robot(0);
  };

  $("#control-ring").click(addModify);

  $(".icon").bind("onmouseover", "reset()");

  $(".icon").click(RandomRobot);

}).call(this);


//# sourceMappingURL=ajax.js.map
