// Generated by LiveScript 1.3.1
(function(){
  var count, sum, isclicked, arr, randomSort, displayTheSpan, addClickEventToAtplus, robotInitial, makeARandomList, buttonsClickingEvent, setBubbleColorToClick, addLeaveEventToAtplus, leaveTheApb;
  $(function(){
    displayTheSpan();
    addClickEventToAtplus();
    addLeaveEventToAtplus();
  });
  count = 0;
  sum = 0;
  isclicked = false;
  arr = [0, 1, 2, 3, 4];
  randomSort = function(a, b){
    if (Math.random() > 0.5) {
      return -1;
    } else {
      return 1;
    }
  };
  displayTheSpan = function(){
    $('.num').css('display', 'none');
  };
  addClickEventToAtplus = function(){
    $('#at-plus-container').click(robotInitial);
  };
  robotInitial = function(){
    var buttonset;
    if (!isclicked) {
      isclicked = true;
      makeARandomList();
      buttonset = document.getElementsByClassName('button');
      buttonsClickingEvent(buttonset[arr[0]]);
    }
  };
  makeARandomList = function(){
    var alpha, str, i$, i;
    arr = arr.sort(randomSort);
    alpha = ['A', 'B', 'C', 'D', 'E'];
    str = '排序顺序： ';
    for (i$ = 0; i$ < 5; ++i$) {
      i = i$;
      str = str + alpha[arr[i]];
    }
    $('.sortinfo').html(str);
  };
  buttonsClickingEvent = function(obj){
    var t, t2, buttonset, i$, len$, i, xhr;
    if (obj !== null) {
      t = obj.childNodes[0];
      t2 = obj;
      buttonset = $('.button');
      if (!$(t.parentNode).hasClass('clicked') && !$(t.parentNode).hasClass('cannotclick')) {
        for (i$ = 0, len$ = buttonset.length; i$ < len$; ++i$) {
          i = buttonset[i$];
          if (i !== t2) {
            $(i).css('background-color', 'rgba(0,0,20,.6)');
            $(i).addClass('cannotclick');
          }
        }
        t.style.display = 'inline';
        $(t.parentNode).addClass('clicked');
        xhr = new XMLHttpRequest();
        xhr.open("GET", "http://localhost:3000/", true);
        xhr.onreadystatechange = function(){
          var n, i$, ref$, len$, i, buttonsets;
          if (xhr.readyState == 4 && xhr.status == 200) {
            t.innerHTML = xhr.responseText;
            n = parseInt(xhr.responseText);
            t.parentNode.style.backgroundColor = 'rgba(0,0,20,.6)';
            if (!isNaN(n)) {
              sum = sum + n;
            }
            console.log(sum);
            count = count + 1;
            console.log(count);
            if (count == 5) {
              setBubbleColorToClick();
              $('.sum').html(sum);
              $('.info').css('background-color', 'rgba(0, 0, 20, .6)');
            }
            for (i$ = 0, len$ = (ref$ = buttonset).length; i$ < len$; ++i$) {
              i = ref$[i$];
              if (i !== t2 && !$(i).hasClass('clicked')) {
                $(i).css('background-color', 'rgba(48, 63, 159, 1)');
                $(i).removeClass('cannotclick');
              }
            }
            buttonsets = document.getElementsByClassName('button');
            if (count !== 5) {
              buttonsClickingEvent(buttonsets[arr[count]]);
            }
          }
        };
        xhr.send(null);
      }
    }
  };
  setBubbleColorToClick = function(){
    var bubble;
    bubble = $('.info');
    bubble.css('background-color', 'rgba(48, 63, 159, 1)');
    bubble.css('transition', 'all 0.6s');
  };
  addLeaveEventToAtplus = function(){
    $('#at-plus-container').mouseleave(leaveTheApb);
  };
  leaveTheApb = function(){
    $('.num').html('...');
    $('.num').css('display', 'none');
    $('.button').removeClass('cannotclick');
    $('.button').removeClass('clicked');
    $('.button').css('background-color', 'rgba(48,63,159,1)');
    $('.info').css('background-color', 'rgba(0,0,20,.6)');
    $('.sum').html('');
    $('.sortinfo').html('');
    sum = 0;
    count = 0;
    isclicked = false;
  };
}).call(this);
