// Generated by LiveScript 1.3.1
(function(){
  var Button, allButtonsAbleToBeClickedToFetchNumber, buttonsInit, bubbleAbleToBeClickedToGetSum, getButtonsSum, addResettingWhenLeavingApb, reset, setBubbleAbleToBeClicked, bubbleInit, S1WaitUserClick, robot, S2RobotClickButtonsFromAToEAndThenClickBubble, S4RobotClickButtonsInARandomOrderAndThenClickBubble;
  $(function(){
    allButtonsAbleToBeClickedToFetchNumber(function(){
      robot.nextAimToClick();
    });
    bubbleAbleToBeClickedToGetSum();
    addResettingWhenLeavingApb();
    robot.initial();
    S1WaitUserClick();
    return S4RobotClickButtonsInARandomOrderAndThenClickBubble();
  });
  Button = (function(){
    Button.displayName = 'Button';
    var prototype = Button.prototype, constructor = Button;
    Button.buttons = [];
    function Button(dom, callback){
      var this$ = this;
      this.dom = dom;
      this.callback = callback;
      this.state = 'enabled';
      this.dom.addClass('enabled');
      this.dom.click(function(){
        if (this$.dom.hasClass('enabled')) {
          this$.constructor.disableOtherButtons(this$);
          this$.wait();
          this$.buttonFetchNumberFromServerAndShow();
        }
      });
      this.constructor.buttons.push(this);
    }
    Button.disableOtherButtons = function(thisButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton) {
          if (button.state !== 'done') {
            if (button.dom[0].children[1].innerHTML === '') {
              button.dom[0].children[1].style.visibility = 'collapse';
            }
            results$.push(button.disable());
          }
        }
      }
      return results$;
    };
    Button.enableOtherButtons = function(thisButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton) {
          if (button.state !== 'done') {
            button.dom[0].children[1].style.visibility = '';
            results$.push(button.enable());
          }
        }
      }
      return results$;
    };
    Button.allButtonsAreDone = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button.state !== 'done') {
          return false;
        }
      }
      return true;
    };
    Button.resetAll = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        button.reset();
      }
    };
    prototype.buttonFetchNumberFromServerAndShow = function(){
      var this$ = this;
      $.get('/', function(number, result){
        if (this$.state === 'waiting') {
          this$.done();
        }
        if (this$.constructor.allButtonsAreDone()) {
          setBubbleAbleToBeClicked();
        }
        this$.constructor.enableOtherButtons(this$);
        this$.buttonShowNumber(number);
        this$.callback();
      });
    };
    prototype.buttonShowNumber = function(number){
      this.dom.find('.unread').text(number);
    };
    prototype.disable = function(){
      this.state = 'disabled';
      this.dom.removeClass('enabled').addClass('disabled');
    };
    prototype.enable = function(){
      this.state = 'enabled';
      this.dom.removeClass('disabled').addClass('enabled');
    };
    prototype.wait = function(){
      this.state = 'waiting';
      this.dom.removeClass('enabled').addClass('waiting');
    };
    prototype.done = function(){
      this.state = 'done';
      this.dom.removeClass('waiting').addClass('done');
    };
    prototype.reset = function(){
      this.state = 'enabled';
      this.dom.removeClass('disabled waiting done').addClass('enabled');
      this.dom.find('.unread').text('');
    };
    return Button;
  }());
  allButtonsAbleToBeClickedToFetchNumber = function(next){
    buttonsInit(next);
  };
  buttonsInit = function(next){
    var buttons, i$, len$, bt, button;
    buttons = $('#control-ring .button');
    for (i$ = 0, len$ = buttons.length; i$ < len$; ++i$) {
      bt = buttons[i$];
      button = new Button($(bt), fn$);
    }
    function fn$(){
      if (typeof next == 'function') {
        next();
      }
    }
  };
  bubbleAbleToBeClickedToGetSum = function(){
    var bubble, this$ = this;
    bubbleInit();
    bubble = $('#info-bar');
    bubble.click(function(){
      if (bubble.hasClass('enabled')) {
        bubble.find('.amount').text(getButtonsSum());
        bubble.removeClass('enabled').addClass('disabled');
      }
    });
  };
  getButtonsSum = function(){
    var sum, i$, ref$, len$, button;
    sum = 0;
    for (i$ = 0, len$ = (ref$ = $('#control-ring .button')).length; i$ < len$; ++i$) {
      button = ref$[i$];
      sum += parseInt(button.children[1].innerHTML.toString());
    }
    return sum;
  };
  addResettingWhenLeavingApb = function(){
    var isEnteringOther;
    isEnteringOther = false;
    $('#info-bar, #control-ring-container, .apb').on('mouseenter', function(){
      isEnteringOther = true;
    });
    $('#info-bar, #control-ring-container').on('mouseleave', function(){
      isEnteringOther = false;
      setTimeout(function(){
        if (!isEnteringOther) {
          reset();
        }
      }, 0);
    });
  };
  reset = function(){
    Button.resetAll();
    bubbleInit();
    robot.reset();
  };
  setBubbleAbleToBeClicked = function(){
    var bubble;
    bubble = $('#info-bar');
    bubble.removeClass('disabled').addClass('enabled');
  };
  bubbleInit = function(){
    var bubble;
    bubble = $('#info-bar');
    bubble.removeClass('enabled').addClass('disabled');
    bubble.find('li.amount').text('');
    bubble.find('li.sequence').text('');
  };
  S1WaitUserClick = function(){
    console.log('waiting user to click...');
  };
  robot = {
    initial: function(){
      this.state = 'waiting';
      this.buttons = $('#control-ring .button');
      this.bubble = $('#info-bar');
      this.order = ["A", "B", "C", "D", "E"];
      this.point = 0;
    },
    startClick: function(){
      this.state = 'running';
      this.nextAimToClick();
    },
    getRandomOrder: function(){
      this.order.sort(function(){
        return Math.random() - 0.3;
      });
    },
    nextAimToClick: function(){
      if (this.state !== 'running') {
        null;
      } else if (this.point < this.order.length) {
        this.getNextButton().click();
      } else if (this.point === this.order.length) {
        this.bubble.click();
      } else {
        this.state = 'waiting';
      }
    },
    showOrder: function(){
      var bubble;
      bubble = $('#info-bar');
      bubble.find('li.sequence').text(this.order.join('->'));
    },
    getNextButton: function(){
      var index;
      index = this.order[this.point++].charCodeAt() - 'A'.charCodeAt();
      return this.buttons[index];
    },
    reset: function(){
      this.point = 0;
      this.state = 'waiting';
    }
  };
  S2RobotClickButtonsFromAToEAndThenClickBubble = function(){
    $('#button .apb').click(function(){
      if (robot.state === 'waiting') {
        reset();
        robot.startClick();
      }
    });
  };
  S4RobotClickButtonsInARandomOrderAndThenClickBubble = function(){
    $('#button .apb').click(function(){
      if (robot.state === 'waiting') {
        reset();
        robot.getRandomOrder();
        robot.showOrder();
        robot.startClick();
      }
    });
  };
}).call(this);
