// Generated by LiveScript 1.3.1
(function(){
  var Button, calculator, robot, S3Robot, clickButtonToGetNumber, clickInforBarToShowResult, moveOutToReset;
  Button = (function(){
    /*构造函数*/
    Button.displayName = 'Button';
    var prototype = Button.prototype, constructor = Button;
    function Button(dom, numberGotCallback){
      var this$ = this;
      this.dom = dom;
      this.numberGotCallback = numberGotCallback;
      this.state = 'unclicked';
      this.dom.addClass('enabled');
      this.dom.find('.unread').addClass('hidden');
      this.dom.click(function(){
        if (this$.dom.hasClass('enabled') && this$.state === 'unclicked') {
          this$.constructor.disableAllOtherButtons(this$);
          this$.wait();
          $.get('/random', function(number){
            this$.showNumber(number);
            this$.constructor.enableAllOtherButtons(this$);
            if (this$.constructor.allButtonIsGot()) {
              this$.constructor.allNumberIsGotCallback();
            }
            this$.numberGotCallback(number);
          });
        }
      });
      this.constructor.buttons.push(this);
    }
    Button.buttons = [];
    Button.disableAllOtherButtons = function(thisButton){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'clicked') {
          button.disable();
        }
      }
    };
    Button.enableAllOtherButtons = function(thisButton){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'clicked') {
          button.enable();
        }
      }
    };
    Button.allButtonIsGot = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button.state === 'unclicked') {
          return false;
        }
      }
      return true;
    };
    Button.resetAll = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        button.reset();
      }
    };
    Button.clickAllButtonAtSameTime = function(){
      var index, bubble, i$, to$;
      index = 0;
      bubble = $('#info-bar');
      for (i$ = 0, to$ = this.buttons.length - 1; i$ <= to$; ++i$) {
        (fn$.call(this, i$));
      }
      function fn$(i){
        var this$ = this;
        this.buttons[i].wait();
        $.get('/random' + i, function(number){
          this$.buttons[i].showNumber(number);
          calculator.add(parseInt(number));
          index += 1;
          if (index === 5) {
            bubble.addClass('enabled');
            bubble.click();
          }
        });
      }
    };
    prototype.wait = function(){
      this.state = 'clicked';
      this.dom.find('.unread').text("...").removeClass('hidden');
    };
    prototype.disable = function(){
      this.state = 'can-not-click';
      this.dom.removeClass('enabled').addClass('disabled');
    };
    prototype.enable = function(){
      this.state = 'unclicked';
      this.dom.removeClass('disabled').addClass('enabled');
    };
    prototype.showNumber = function(number){
      this.dom.addClass('disabled');
      this.dom.find('.unread').text(number);
    };
    prototype.reset = function(){
      this.state = 'unclicked';
      this.dom.removeClass('disabled').addClass('enabled');
      this.dom.find('.unread').text("").addClass('hidden');
    };
    return Button;
  }());
  /*计算总和*/
  calculator = {
    Sum: 0,
    add: function(number){
      return this.Sum += parseInt(number);
    },
    reset: function(){
      this.Sum = 0;
    }
  };
  robot = {
    clickAllButtonAtSameTime: function(){
      Button.clickAllButtonAtSameTime();
    }
  };
  S3Robot = function(){
    var atPlus;
    atPlus = $('#button .apb');
    atPlus.click(function(){
      robot.clickAllButtonAtSameTime();
    });
  };
  /*生成button对象*/
  clickButtonToGetNumber = function(){
    var buttons, i$, len$;
    buttons = $('#control-ring .button');
    for (i$ = 0, len$ = buttons.length; i$ < len$; ++i$) {
      (fn$.call(this, i$, buttons[i$]));
    }
    function fn$(i, dom){
      var button;
      button = new Button($(dom), function(number){
        calculator.add(number);
      });
    }
  };
  /*点击info-bar显示总和*/
  clickInforBarToShowResult = function(){
    var bubble;
    bubble = $('#info-bar');
    bubble.addClass('disabled');
    Button.allNumberIsGotCallback = function(){
      return bubble.removeClass('disabled').addClass('enabled');
    };
    bubble.click(function(){
      if (bubble.hasClass('enabled')) {
        bubble.removeClass('enabled').addClass('disabled');
        bubble.find('.amount').text(calculator.Sum);
      }
    });
  };
  /*移开对应区域重置*/
  moveOutToReset = function(){
    var area;
    area = $('#bottom-positioner');
    area.on('mouseleave', function(event){
      Button.resetAll();
      $('#info-bar').removeClass('enabled').addClass('disabled');
      $('#info-bar').find('.amount').text('');
      $('#info-bar').find('.sequence').text('');
      calculator.reset();
    });
  };
  window.onload = function(){
    clickButtonToGetNumber();
    clickInforBarToShowResult();
    moveOutToReset();
    S3Robot();
  };
}).call(this);
