// Generated by LiveScript 1.3.1
(function(){
  var clearAll, boomAddClick, liAddClick, liGetNumber, disableOtherLi, callback, enableBoomClick, enableOtherLi;
  window.onload = function(){
    boomAddClick();
    liAddClick();
    clearAll();
  };
  clearAll = function(){
    document.getElementById('at-plus-container').onmouseleave = function(){
      location.reload();
    };
  };
  boomAddClick = function(){
    var icon_, unread_, sum;
    icon_ = document.getElementById("info-bar");
    unread_ = document.getElementsByClassName("unread");
    sum = 0;
    icon_.onclick = function(){
      var i$, ref$, len$, item, show;
      if (enableBoomClick()) {
        for (i$ = 0, len$ = (ref$ = unread_).length; i$ < len$; ++i$) {
          item = ref$[i$];
          sum += Number(item.innerHTML);
        }
        show = document.getElementsByClassName("data");
        show[0].innerHTML = String(sum);
      }
    };
  };
  liAddClick = function(){
    var lis, i$, len$, item;
    lis = document.getElementsByTagName("li");
    for (i$ = 0, len$ = lis.length; i$ < len$; ++i$) {
      item = lis[i$];
      item.onclick = fn$;
    }
    function fn$(){
      if (this.success !== "after" && this.success !== "false") {
        this.success = "after";
        liGetNumber(this);
      }
    }
  };
  liGetNumber = function(li){
    var span, xmlHttp;
    disableOtherLi();
    span = li.getElementsByTagName("span");
    span[0].innerHTML = "...";
    span[0].style.display = "block";
    xmlHttp = new XMLHttpRequest();
    xmlHttp.open("get", "/", true);
    if (xmlHttp !== null) {
      xmlHttp.send(null);
      return xmlHttp.onreadystatechange = function(){
        if (xmlHttp.readyState === 4 && xmlHttp.status === 200) {
          return callback(xmlHttp.responseText, li);
        }
      };
    }
  };
  disableOtherLi = function(){
    var lis, i$, len$, item;
    lis = document.getElementsByTagName("li");
    for (i$ = 0, len$ = lis.length; i$ < len$; ++i$) {
      item = lis[i$];
      if (item.success !== "after" && item.success !== "false") {
        item.style.backgroundColor = "gray";
        item.success = "false";
      }
    }
  };
  callback = function(text, li){
    var span;
    span = li.getElementsByTagName("span");
    span[0].innerHTML = String(text);
    li.style.backgroundColor = "gray";
    enableOtherLi();
    return enableBoomClick();
  };
  enableBoomClick = function(){
    var unreads, success, i$, len$, item, icon_;
    unreads = document.getElementsByClassName("unread");
    success = true;
    for (i$ = 0, len$ = unreads.length; i$ < len$; ++i$) {
      item = unreads[i$];
      if (item.innerHTML === "") {
        success = false;
      }
    }
    if (success === true) {
      icon_ = document.getElementById("info-bar");
      icon_.style.backgroundColor = "#21479D";
      return true;
    } else {
      return false;
    }
  };
  enableOtherLi = function(){
    var lis, i$, len$, item;
    lis = document.getElementsByTagName("li");
    for (i$ = 0, len$ = lis.length; i$ < len$; ++i$) {
      item = lis[i$];
      if (item.success !== "after") {
        item.success = "true";
        item.style.backgroundColor = "#21479D";
      }
    }
  };
}).call(this);
