// Generated by LiveScript 1.3.1
(function(){
  var makeAllButtonCanBeClicked, rebornAllButtons, makeButtonDisable, makeButtonEnable, getNumber, waitNumber, getResult;
  window.onload = function(){
    makeAllButtonCanBeClicked();
    $("button").onmouseleave = rebornAllButtons;
  };
  makeAllButtonCanBeClicked = function(){
    var abcde, i$, to$, i;
    abcde = $("control-ring").children;
    for (i$ = 0, to$ = abcde.length; i$ < to$; ++i$) {
      i = i$;
      abcde[i].addEventListener('click', getNumber);
    }
  };
  rebornAllButtons = function(){
    var abcde, i$, to$, i, bubble;
    abcde = $("control-ring").children;
    for (i$ = 0, to$ = abcde.length; i$ < to$; ++i$) {
      i = i$;
      if (abcde[i].childNodes.length === 2) {
        abcde[i].removeChild(abcde[i].childNodes[1]);
      }
      makeButtonEnable(abcde[i]);
    }
    bubble = $("info");
    bubble.removeEventListener('click', getResult);
    bubble.style.backgroundColor = 'grey';
    bubble.innerHTML = "";
  };
  makeButtonDisable = function(button){
    button.removeEventListener('click', getNumber);
    button.style.backgroundColor = 'grey';
  };
  makeButtonEnable = function(button){
    button.addEventListener('click', getNumber);
    button.style.backgroundColor = 'blue';
  };
  getNumber = function(){
    var rc, abcde, i$, to$, i, thisbutton, xmlhttp;
    rc = document.createElement('span');
    rc.innerText = '...';
    rc.className = 'redcircle';
    rc.style.fontSize = '5px';
    this.appendChild(rc);
    abcde = $("control-ring").children;
    for (i$ = 0, to$ = abcde.length; i$ < to$; ++i$) {
      i = i$;
      if (abcde[i] !== this) {
        makeButtonDisable(abcde[i]);
      }
    }
    thisbutton = this;
    /* sent-request-to-server rc,thisbutton */
    if (window.XMLHttpRequest) {
      xmlhttp = new XMLHttpRequest();
    } else {
      xmlhttp = new ActiveXObject('Microsoft.XMLHTTP');
    }
    xmlhttp.onreadystatechange = function(){
      if (xmlhttp.readyState === 4 && xmlhttp.status === 200) {
        rc.innerText = xmlhttp.responseText;
        waitNumber(thisbutton);
      }
    };
    xmlhttp.open('GET', '/', true);
    xmlhttp.send();
  };
  /*sent-request-to-server = (rc, thisbutton) !->
  	$.get('/', (data, status) !->
  					rc.innerText = xmlhttp.data
  					wait-number thisbutton)*/
  waitNumber = function(thisbutton){
    var flag, abcde, i$, to$, i, result;
    flag = 1;
    abcde = $("control-ring").children;
    for (i$ = 0, to$ = abcde.length; i$ < to$; ++i$) {
      i = i$;
      if (abcde[i].childNodes.length === 1) {
        makeButtonEnable(abcde[i]);
        flag = 0;
      }
      makeButtonDisable(thisbutton);
      if (flag === 1) {
        result = $("info");
        result.addEventListener('click', getResult);
        result.style.backgroundColor = 'blue';
      }
    }
  };
  getResult = function(){
    var abcde, sum, i$, to$, i;
    abcde = $("control-ring").children;
    sum = 0;
    for (i$ = 0, to$ = abcde.length; i$ < to$; ++i$) {
      i = i$;
      sum = sum + parseInt(abcde[i].lastChild.innerText);
    }
    this.innerHTML = sum;
    this.removeEventListener('click', getResult);
    this.style.backgroundColor = 'grey';
  };
}).call(this);
