// Generated by CoffeeScript 1.8.0
(function() {
  var FiveFingerDragon, addModify, calculate, callback, callback3, color, disable, enable, k, modifyLabel, reset, setBubbleEnable, setLabel;

  k = $("#control-ring li");

  reset = function() {
    return 0;
  };

  modifyLabel = function(unread, data) {
    unread.innerHTML = data;
    return 0;
  };

  enable = function() {
    var li, liList, _i, _len;
    liList = $("#control-ring li");
    for (_i = 0, _len = liList.length; _i < _len; _i++) {
      li = liList[_i];
      if (!$(li).find("[class=unread]").get(0)) {
        color("rgba(61,40,166,1)", li);
      }
    }
    $("#control-ring").click(addModify);
    return 0;
  };

  calculate = function() {
    var add, span, sum, _i, _len, _ref;
    sum = 0;
    add = function(span) {
      return sum = sum + parseInt(span.innerHTML);
    };
    _ref = $("[class=unread] span");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      span = _ref[_i];
      add(span);
    }
    $("#cal-result").get(0).innerHTML = sum;
    $(".info").css("background-color", "grey");
    return $("#info-bar").unbind("click");
  };

  setBubbleEnable = function() {
    color("rgba(61,40,166,1)", ".info");
    return $("#info-bar").click(calculate);
  };

  callback = function(data, textStatus) {
    var UnreadList, unread, _i, _len;
    UnreadList = $("[class=unread] span");
    for (_i = 0, _len = UnreadList.length; _i < _len; _i++) {
      unread = UnreadList[_i];
      if (unread.innerHTML === "...") {
        modifyLabel(unread, data);
      }
    }
    enable();
    if ($("li [class=unread]").length === 5) {
      setBubbleEnable();
      $("#control-ring").unbind("click");
    }
    return 0;
  };

  callback3 = function(data, textStatus) {
    var UnreadList, unread, _i, _len;
    UnreadList = $("[class=unread] span");
    for (_i = 0, _len = UnreadList.length; _i < _len; _i++) {
      unread = UnreadList[_i];
      if (!(unread.innerHTML === "...")) {
        continue;
      }
      modifyLabel(unread, data);
      break;
    }
    enable();
    if ($("li [class=unread]").length === 5) {
      calculate();
    }
    return 0;
  };

  color = function(colorName, li) {
    return $(li).css("background-color", "" + colorName);
  };

  disable = function() {
    var li, liList, _i, _len;
    liList = $("#control-ring li");
    for (_i = 0, _len = liList.length; _i < _len; _i++) {
      li = liList[_i];
      color("grey", li);
    }
    $("#control-ring").unbind("click");
    return 0;
  };

  addModify = function(e) {
    var tar;
    tar = e.target || window.target;
    if (!$(tar).find("span").get(0)) {
      tar = tar.parentNode;
    }
    if (!$(tar).find("[class=unread]").get(0)) {
      setLabel(tar);
      $.get("/", callback);
      return disable();
    }
  };

  setLabel = function(tar) {
    var unread;
    unread = $("<div class='unread'><span>...</span></div>");
    $(tar).append(unread.get(0));
    return 0;
  };

  FiveFingerDragon = function() {
    var clickBtn, li, liList, _i, _len, _results;
    clickBtn = function(li) {
      setLabel(li);
      $.get("/", callback3);
      return disable();
    };
    liList = $("#control-ring li");
    _results = [];
    for (_i = 0, _len = liList.length; _i < _len; _i++) {
      li = liList[_i];
      if (!$(li).find("[class=unread]").get(0)) {
        _results.push(clickBtn(li));
      }
    }
    return _results;
  };

  $("#control-ring").click(addModify);

  $(".icon").bind("onmouseover", "reset()");

  $(".icon").click(FiveFingerDragon);

}).call(this);


//# sourceMappingURL=ajax.js.map
