// Generated by LiveScript 1.3.1
(function(){
  var Button, calculator, robot, S2Robot, clickButtonToGetNumber, clickInforBarToShowResult, moveOutToReset;
  Button = (function(){
    /*构造函数*/
    Button.displayName = 'Button';
    var prototype = Button.prototype, constructor = Button;
    function Button(dom, numberGotCallback){
      var this$ = this;
      this.dom = dom;
      this.numberGotCallback = numberGotCallback;
      this.state = 'unclicked';
      this.dom.addClass('enabled');
      this.dom.find('.unread').addClass('hidden');
      this.dom.click(function(){
        if (this$.dom.hasClass('enabled') && this$.state === 'unclicked') {
          this$.constructor.disableAllOtherButtons(this$);
          this$.wait();
          $.get('/random', function(number){
            this$.showNumber(number);
            this$.constructor.enableAllOtherButtons(this$);
            if (this$.constructor.allButtonIsGot()) {
              this$.constructor.allNumberIsGotCallback();
            }
            this$.numberGotCallback(number);
          });
        }
      });
      this.constructor.buttons.push(this);
    }
    Button.buttons = [];
    Button.disableAllOtherButtons = function(thisButton){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'clicked') {
          button.disable();
        }
      }
    };
    Button.enableAllOtherButtons = function(thisButton){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'clicked') {
          button.enable();
        }
      }
    };
    Button.allButtonIsGot = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button.state === 'unclicked') {
          return false;
        }
      }
      return true;
    };
    Button.resetAll = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        button.reset();
      }
    };
    prototype.wait = function(){
      this.state = 'clicked';
      this.dom.find('.unread').text("...").removeClass('hidden');
    };
    prototype.disable = function(){
      this.state = 'can-not-click';
      this.dom.removeClass('enabled').addClass('disabled');
    };
    prototype.enable = function(){
      this.state = 'unclicked';
      this.dom.removeClass('disabled').addClass('enabled');
    };
    prototype.showNumber = function(number){
      this.dom.addClass('disabled');
      this.dom.find('.unread').text(number);
    };
    prototype.reset = function(){
      this.state = 'unclicked';
      this.dom.removeClass('disabled').addClass('enabled');
      this.dom.find('.unread').text("").addClass('hidden');
    };
    return Button;
  }());
  /*计算总和*/
  calculator = {
    Sum: 0,
    add: function(number){
      return this.Sum += parseInt(number);
    },
    reset: function(){
      this.Sum = 0;
    }
  };
  /*robot机器人, 由于不知道该怎么设计robot，此部分是仿造老师的代码的*/
  robot = {
    initial: function(){
      this.sequence = ["A", "B", "C", "D", "E"];
      this.index = 0;
      this.buttons = $('#control-ring .button');
      return this.bubble = $('#info-bar');
    },
    disorderSequence: function(){
      this.sequence.sort(function(){
        return Math.random() > 0.5;
      });
    },
    showSequence: function(){
      $('#info-bar').find('.sequence').text(this.sequence.join(', '));
    },
    clickButtonBySequence: function(){
      if (this.index === this.sequence.length) {
        this.bubble.click();
      } else {
        this.getNextButton().click();
      }
    },
    getNextButton: function(){
      var index2;
      index2 = this.sequence[this.index++].charCodeAt() - 'A'.charCodeAt();
      return this.buttons[index2];
    }
  };
  S2Robot = function(){
    var atPlus;
    atPlus = $('#button .apb');
    atPlus.click(function(){
      robot.clickButtonBySequence();
    });
  };
  /*生成button对象,由于需要自动点击，所以将该函数变成带参数的函数，而参数为robot的点击函数*/
  clickButtonToGetNumber = function(next){
    var buttons, i$, len$, results$ = [];
    buttons = $('#control-ring .button');
    for (i$ = 0, len$ = buttons.length; i$ < len$; ++i$) {
      results$.push((fn$.call(this, i$, buttons[i$])));
    }
    return results$;
    function fn$(i, dom){
      var button;
      return button = new Button($(dom), function(number){
        calculator.add(number);
        next();
      });
    }
  };
  /*点击显示info-bar总和*/
  clickInforBarToShowResult = function(){
    var bubble;
    bubble = $('#info-bar');
    bubble.addClass('disabled');
    Button.allNumberIsGotCallback = function(){
      return bubble.removeClass('disabled').addClass('enabled');
    };
    bubble.click(function(){
      if (bubble.hasClass('enabled')) {
        bubble.removeClass('enabled').addClass('disabled');
        bubble.find('.amount').text(calculator.Sum);
      }
    });
  };
  /*移开相应区域重置*/
  moveOutToReset = function(){
    var area;
    area = $('#bottom-positioner');
    area.on('mouseleave', function(event){
      Button.resetAll();
      $('#info-bar').removeClass('enabled').addClass('disabled');
      $('#info-bar').find('.amount').text('');
      $('#info-bar').find('.sequence').text('');
      robot.initial();
      calculator.reset();
    });
  };
  window.onload = function(){
    clickButtonToGetNumber(function(){
      robot.clickButtonBySequence();
    });
    clickInforBarToShowResult();
    moveOutToReset();
    robot.initial();
    S2Robot();
  };
}).call(this);
