// Generated by CoffeeScript 1.9.0
(function() {
  var able_to_calculate, calculate_result, change_the_state, clicked_and_get_num, disable, disable_all_button, enable, enable_all_buttons, enable_the_left_button, reset, show_result;

  $(function() {
    reset();
    $('.button').bind('click', function(event) {
      if (($(this).hasClass("can_click")) || $(this).hasClass("OK")) {
        return clicked_and_get_num(this);
      }
    });
    $('#bottom-positioner').bind('mouseleave', function(event) {
      return reset();
    });
    return $(".icon").bind('click', function(event) {
      if (able_to_calculate()) {
        return calculate_result();
      }
    });
  });

  reset = function() {
    enable_all_buttons();
    $(".info").eq(0).css("background-color", "#7E7E7E");
    $("#info-bar span").eq(0).text("");
    return typeof req !== "undefined" && req !== null ? req.abort() : void 0;
  };

  enable_all_buttons = function() {
    var i, _i, _ref, _results;
    $(".button span").hide();
    $(".button span").text("...");
    $(".button").removeClass("OK");
    _results = [];
    for (i = _i = 0, _ref = $(".button").size() - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      _results.push(enable($(".button").get(i)));
    }
    return _results;
  };

  disable_all_button = function(button) {
    var i, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = $(".button").size() - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      _results.push(disable($(".button").get(i)));
    }
    return _results;
  };

  enable_the_left_button = function() {
    var i, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = $(".button").size() - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (!$(".button").eq(i).hasClass("OK")) {
        _results.push(enable($(".button").get(i)));
      }
    }
    return _results;
  };

  clicked_and_get_num = function(button) {
    ($(button)).children().show();
    disable_all_button(button);
    return window.req = $.ajax({
      url: "/",
      type: 'GET',
      dataType: "html",
      error: function(jqXHR, textStatus, errorThrown) {
        return console.log("AJAX Error: " + textStatus);
      },
      success: function(data, textStatus, jqXHR) {
        change_the_state(button, data);
        enable_the_left_button();
        if (able_to_calculate()) {
          return $(".info").eq(0).css("background-color", "#2D3AA4");
        }
      }
    });
  };

  change_the_state = function(button, num) {
    ($(button)).children().text(num);
    $(button).addClass("OK");
    return disable(button);
  };

  enable = function(button) {
    $(button).css("background-color", "#2D3AA4");
    return $(button).addClass("can_click");
  };

  disable = function(button) {
    $(button).css("background-color", "#7E7E7E");
    return $(button).removeClass("can_click");
  };

  able_to_calculate = function() {
    var i, _i, _ref;
    for (i = _i = 0, _ref = $(".button").size() - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (!$(".button").eq(i).hasClass("OK")) {
        return false;
      }
    }
    return true;
  };

  calculate_result = function() {
    var i, sum, _i, _ref;
    sum = 0;
    for (i = _i = 0, _ref = $(".button span").size() - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      sum += parseInt($(".button span").eq(i).text());
    }
    return show_result(sum);
  };

  show_result = function(sum) {
    return $("#info-bar span").eq(0).text(sum.toString());
  };

}).call(this);
