// Generated by LiveScript 1.3.1
(function(){
  var Bubble, Button, reset;
  Bubble = (function(){
    Bubble.displayName = 'Bubble';
    var prototype = Bubble.prototype, constructor = Bubble;
    function Bubble(){
      $('#info-bar').click(function(){
        if ($('#info-bar').css("background-color") === "rgb(0, 0, 255)") {
          $('#info-bar').text(Button.sum);
          $('#info-bar').css("background-color", "gray");
        }
      });
    }
    Bubble.reset = function(){
      $('#info-bar').text('');
      $('#info-bar').css("background-color", "gray");
    };
    return Bubble;
  }());
  Button = (function(){
    Button.displayName = 'Button';
    var prototype = Button.prototype, constructor = Button;
    Button.sum = 0;
    Button.buttons = [];
    prototype.disable = function(){
      this.state = 'disabled';
      $(this.dom).css("background-color", "gray");
    };
    prototype.enable = function(){
      this.state = 'enabled';
      $(this.dom).css("background-color", "blue");
    };
    prototype.waiting = function(){
      this.state = 'waiting';
      $(this.dom).find('.unread').css("opacity", "0.7");
      $(this.dom).find('.unread').text('...');
    };
    Button.disableOthers = function(thisButton){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'done') {
          button.disable();
        }
      }
    };
    Button.enableOthers = function(thisButton){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'done') {
          button.enable();
        }
      }
    };
    Button.allButtonDone = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button.state !== 'done') {
          return false;
        }
      }
      return true;
    };
    Button.reset = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        button.state = 'enabled';
        button.dom.css("background-color", "blue");
        button.dom.find('.unread').text('');
        button.dom.find('.unread').css("opacity", "0");
      }
      this.sum = 0;
    };
    prototype.getNumber = function(){
      var this$ = this;
      $.get('/', function(number){
        if (this$.state === 'waiting') {
          this$.state = 'done';
          this$.dom.css("background-color", "gray");
          this$.constructor.enableOthers(this$);
          this$.dom.find('.unread').text(number);
          this$.constructor.sum += parseInt(number);
          if (this$.constructor.allButtonDone()) {
            $('#info-bar').css("background-color", "blue");
          }
        }
      });
    };
    function Button(dom){
      var this$ = this;
      this.dom = dom;
      this.state = 'enabled';
      this.dom.click(function(){
        if (this$.state === 'enabled') {
          this$.constructor.disableOthers(this$);
          this$.waiting();
          this$.getNumber();
        }
      });
      this.constructor.buttons.push(this);
    }
    return Button;
  }());
  reset = function(){
    Button.reset();
    Bubble.reset();
  };
  $(function(){
    var i$, ref$, len$, bubble, bindingResetWhenLeaveApb, leave;
    for (i$ = 0, len$ = (ref$ = $('#control-ring .button')).length; i$ < len$; ++i$) {
      (fn$.call(this, i$, ref$[i$]));
    }
    bubble = new Bubble();
    bindingResetWhenLeaveApb = function(){};
    leave = false;
    $('#button').on('mouseenter', function(){
      leave = true;
    });
    $('#button').on('mouseleave', function(event){
      leave = false;
      reset();
    });
    bindingResetWhenLeaveApb();
    function fn$(i, dom){
      var button;
      button = new Button($(dom));
    }
  });
}).call(this);
