// Generated by LiveScript 1.3.1
(function(){
  var Button, calcuator, robot, reset, addClickToGetNumberWithAjaxToAllNumbers, addClickToCalculateSumOfAllButtonsAndShow, addResetToLeaveAtPlusArea, s1WaitingUserClick, s5IndependentBehavior;
  Button = (function(){
    Button.displayName = 'Button';
    var prototype = Button.prototype, constructor = Button;
    Button.buttons = [];
    Button.disableOtherButtons = function(currentButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== currentButton && button.state !== 'done') {
          results$.push(button.disable());
        }
      }
      return results$;
    };
    Button.enableOtherButtons = function(currentButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== currentButton && button.state !== 'done') {
          results$.push(button.enable());
        }
      }
      return results$;
    };
    Button.allButtonGotNumber = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button.state !== 'done') {
          return false;
        }
      }
      $('#info-bar').removeClass('disabled').addClass('enabled');
      return true;
    };
    Button.resetAllButtons = function(){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        results$.push(button.reset());
      }
      return results$;
    };
    function Button(dom, goodMsg, badMsg, callback){
      var this$ = this;
      this.dom = dom;
      this.goodMsg = goodMsg;
      this.badMsg = badMsg;
      this.callback = callback;
      this.state = 'enabled';
      this.request;
      this.name = this.dom.text();
      this.dom.click(function(){
        if (this$.state === 'enabled') {
          this$.constructor.disableOtherButtons(this$);
          this$.wait();
          this$.getNumberAndShow();
        }
      });
      this.constructor.buttons.push(this);
    }
    prototype.getNumberAndShow = function(){
      var this$ = this;
      this.request = $.get('/' + Math.random(), function(number){
        this$.done();
        this$.constructor.allButtonGotNumber();
        this$.constructor.enableOtherButtons(this$);
        this$.showNumber(number);
        this$.exceptionHandler(number);
      });
    };
    prototype.showNumber = function(number){
      this.dom.find('.unread').text(number);
    };
    prototype.showMessage = function(){
      $('#message').text(this.name + ": " + this.goodMsg);
    };
    prototype.exceptionHandler = function(number){
      var error;
      if (Math.random() > 0.5) {
        this.showMessage();
        this.callback(error = null, number);
      } else {
        this.callback({
          message: this.badMsg,
          data: number
        });
      }
    };
    prototype.disable = function(){
      this.state = 'disabled';
      this.dom.removeClass('enabled').addClass('disabled');
    };
    prototype.enable = function(){
      this.state = 'enabled';
      this.dom.removeClass('disabled').addClass('enabled');
    };
    prototype.wait = function(){
      this.state = 'wait';
      this.dom.removeClass('disabled').addClass('wait');
      this.dom.find('.unread').text("...");
    };
    prototype.done = function(){
      this.state = 'done';
      this.dom.removeClass('wait').addClass('done');
    };
    prototype.reset = function(){
      this.state = 'enabled';
      if (this.request) {
        this.request.abort();
      }
      this.dom.removeClass('disabled wait done').addClass('enabled');
      this.dom.find('.unread').text('');
    };
    return Button;
  }());
  calcuator = {
    sum: 0,
    add: function(number){
      return this.sum += parseInt(number);
    },
    reset: function(){
      this.sum = 0;
    }
  };
  robot = {
    init: function(){
      this.buttons = $('#control-ring .button');
      this.bigBubble = $('#info-bar');
      this.sequence = ["A", "B", "C", "D", "E"];
      this.current = 0;
    },
    shuffleOrder: function(){
      this.sequence.sort(function(){
        if (Math.random() > 0.5) {
          return -1;
        } else {
          return 1;
        }
      });
    },
    showOrder: function(){
      var order, i$, ref$, len$, i;
      order = '';
      for (i$ = 0, len$ = (ref$ = this.sequence).length; i$ < len$; ++i$) {
        i = ref$[i$];
        order += i;
      }
      this.bigBubble.find('.info').text(order);
    },
    clickNext: function(){
      if (this.current === this.sequence.length) {
        this.bigBubble.click();
      } else {
        this.getNextButton().click();
      }
    },
    getNextButton: function(){
      var next;
      next = this.sequence[this.current].charCodeAt() - 'A'.charCodeAt();
      this.current++;
      return this.buttons[next];
    },
    clickAll: function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        button.click();
        Button.enableOtherButtons(button);
        this.current++;
      }
      this.clickNext();
    }
  };
  reset = function(){
    var bigBubble;
    bigBubble = $('#info-bar');
    calcuator.reset();
    robot.init();
    Button.resetAllButtons();
    bigBubble.removeClass('enabled').addClass('disabled');
    bigBubble.find('.info').text('');
    $('#message').text('');
  };
  $(function(){
    addClickToGetNumberWithAjaxToAllNumbers();
    addClickToCalculateSumOfAllButtonsAndShow();
    addResetToLeaveAtPlusArea();
    s1WaitingUserClick();
    return s5IndependentBehavior();
  });
  addClickToGetNumberWithAjaxToAllNumbers = function(){
    var goodMsg, badMsg, i$, ref$, len$, results$ = [];
    goodMsg = ['这是个天大的秘密', '我不知道', '你不知道', '他不知道', '才怪'];
    badMsg = ['这不是个天大的秘密', '我知道', '你知道', '他知道', '才怪个鬼'];
    for (i$ = 0, len$ = (ref$ = $('#control-ring .button')).length; i$ < len$; ++i$) {
      results$.push((fn$.call(this, i$, ref$[i$])));
    }
    return results$;
    function fn$(i, btn){
      var button;
      return button = new Button($(btn), goodMsg[i], badMsg[i], function(error, number){
        if (error) {
          $('#message').text("Error! " + button.name + ": " + error.message);
          number = error.data;
        }
        calcuator.add(number);
        if (robot.current !== 0) {
          robot.clickNext();
        }
      });
    }
  };
  addClickToCalculateSumOfAllButtonsAndShow = function(){
    var bigBubble;
    bigBubble = $('#info-bar');
    bigBubble.addClass('disabled');
    return bigBubble.click(function(){
      if (bigBubble.hasClass('enabled')) {
        bigBubble.find('.info').text(calcuator.sum);
        bigBubble.addClass('disabled');
        $('#message').text("楼主异步调用战斗力感人，目测不超过" + calcuator.sum);
      }
    });
  };
  addResetToLeaveAtPlusArea = function(){
    $('#at-plus-container').on('mouseleave', function(){
      reset();
    });
  };
  s1WaitingUserClick = function(){
    console.log("wait user click...");
  };
  s5IndependentBehavior = function(){
    robot.init();
    return $('#button .apb').click(function(){
      robot.shuffleOrder();
      robot.showOrder();
      robot.clickNext();
    });
  };
}).call(this);
