// Generated by LiveScript 1.3.1
(function(){
  var Handler, Bubble, Reset, initBigBubble, initAllSmallCirlces, initResetButton;
  Handler = (function(){
    Handler.displayName = 'Handler';
    var prototype = Handler.prototype, constructor = Handler;
    Handler.allCircles = [];
    Handler.isWorking = false;
    Handler.disableOtherCircles = function(nowCircle){
      var i$, ref$, len$, circle;
      for (i$ = 0, len$ = (ref$ = this.allCircles).length; i$ < len$; ++i$) {
        circle = ref$[i$];
        if (circle !== nowCircle && circle.status !== 'finished') {
          if (circle.status !== 'auto') {
            circle.status = 'unclickable';
          }
          circle.theCircle.removeClass('clickable');
        }
      }
    };
    Handler.enableOtherCircles = function(nowCircle){
      var i$, ref$, len$, circle;
      for (i$ = 0, len$ = (ref$ = this.allCircles).length; i$ < len$; ++i$) {
        circle = ref$[i$];
        if (circle !== nowCircle && circle.status !== 'finished') {
          if (circle.status !== 'auto') {
            circle.status = 'clickable';
            circle.theCircle.addClass('clickable');
          }
        }
      }
    };
    Handler.checkIfAllFinished = function(){
      var i$, ref$, len$, circle;
      for (i$ = 0, len$ = (ref$ = this.allCircles).length; i$ < len$; ++i$) {
        circle = ref$[i$];
        if (circle.status !== 'finished') {
          return false;
        }
      }
      return true;
    };
    function Handler(theCircle, bubble){
      var this$ = this;
      this.theCircle = theCircle;
      this.bubble = bubble;
      this.status = "clickable";
      this.theCircle.addClass('clickable');
      this.constructor.allCircles.push(this);
      this.theCircle.click(function(){
        if (this$.status !== 'finished' && this$.status !== 'acquiring' && this$.status !== 'unclickable') {
          this$.constructor.disableOtherCircles(this$);
          if (this$.status !== 'auto') {
            this$.status = 'acquiring';
          }
          this$.theCircle.append('<span class="unread" style="font-size:5px">..</span>');
          this$.getNumber();
        }
      });
    }
    prototype.getNumber = function(){
      var this$ = this;
      $.get('/' + Math.random(), function(num, state){
        var flag;
        if (this$.status === 'acquiring' || this$.status === 'auto') {
          flag = 0;
          if (this$.status === 'auto') {
            flag = 1;
          }
          this$.theCircle.find('.unread').text(num);
          this$.status = 'finished';
          this$.theCircle.removeClass('clickable');
          this$.constructor.enableOtherCircles(this$.theCircle);
          if (this$.constructor.checkIfAllFinished()) {
            this$.bubble.setClickable();
            if (flag === 1) {
              this$.bubble.sumAllAndShow();
            }
          }
        }
      });
    };
    prototype.reset = function(){
      var init;
      this.status = 'clickable';
      this.theCircle.addClass('clickable');
      init = this.theCircle.text()[0];
      this.theCircle.text(init);
      this.constructor.isWorking = false;
    };
    return Handler;
  }());
  Bubble = (function(){
    Bubble.displayName = 'Bubble';
    var prototype = Bubble.prototype, constructor = Bubble;
    function Bubble(theBubble){
      var this$ = this;
      this.theBubble = theBubble;
      this.status = 'unclickable';
      this.theBubble.removeClass('clickable');
      this.theBubble.click(function(){
        if (this$.status === 'clickable') {
          this$.sumAllAndShow();
        }
      });
    }
    prototype.setClickable = function(){
      this.status = 'clickable';
      this.theBubble.addClass('clickable');
    };
    prototype.sumAllAndShow = function(){
      var sum, i$, ref$, len$, circle, tem;
      sum = 0;
      for (i$ = 0, len$ = (ref$ = Handler.allCircles).length; i$ < len$; ++i$) {
        circle = ref$[i$];
        tem = circle.theCircle.find('.unread').text();
        sum += parseInt(tem);
      }
      this.theBubble.text(sum);
      this.theBubble.status = 'unclickable';
      this.theBubble.removeClass('clickable');
    };
    prototype.reset = function(){
      this.status = 'unclickable';
      this.theBubble.removeClass('clickable');
      this.theBubble.text('');
    };
    return Bubble;
  }());
  Reset = (function(){
    Reset.displayName = 'Reset';
    var prototype = Reset.prototype, constructor = Reset;
    function Reset(theReset, bubble){
      var this$ = this;
      this.theReset = theReset;
      this.bubble = bubble;
      this.theReset.mouseleave(function(){
        var i$, ref$, len$, circle;
        for (i$ = 0, len$ = (ref$ = Handler.allCircles).length; i$ < len$; ++i$) {
          circle = ref$[i$];
          circle.reset();
        }
        this$.bubble.reset();
      });
    }
    return Reset;
  }());
  initBigBubble = function(){
    var bubble, bubbleHandler;
    bubble = $('#info-bar');
    bubbleHandler = new Bubble($(bubble));
    return bubbleHandler;
  };
  initAllSmallCirlces = function(bubble){
    var circles, i$, len$;
    circles = $('#control-ring .button');
    for (i$ = 0, len$ = circles.length; i$ < len$; ++i$) {
      (fn$.call(this, circles[i$]));
    }
    function fn$(circle){
      var nowCircle;
      nowCircle = new Handler($(circle), bubble);
    }
  };
  initResetButton = function(bubble){
    var reset, resetHandler;
    reset = $('#bottom-positioner');
    resetHandler = new Reset($(reset), bubble);
  };
  $(function(){
    var bubble, circles, seq;
    bubble = initBigBubble();
    initAllSmallCirlces(bubble);
    initResetButton(bubble);
    circles = $('#control-ring .button');
    seq = [0, 1, 2, 3, 4];
    return $('#button .apb').click(function(){
      var i$, ref$, len$;
      if (Handler.isWorking === false) {
        Handler.isWorking = true;
        for (i$ = 0, len$ = (ref$ = Handler.allCircles).length; i$ < len$; ++i$) {
          (fn$.call(this, ref$[i$]));
        }
        for (i$ = 0, len$ = (ref$ = seq).length; i$ < len$; ++i$) {
          (fn1$.call(this, ref$[i$]));
        }
      }
      function fn$(circle){
        if (circle.status !== 'finished') {
          circle.status = 'auto';
        }
      }
      function fn1$(now){
        circles[now].click();
      }
    });
  });
}).call(this);
