// Generated by LiveScript 1.3.1
(function(){
  var count, sum, displayTheSpan, clickToFetchANumber, buttonsEvent, setBubbleColorToClick, clickToCalculateTheSum, calculateTheSum, mouseLeaveTheAtplus, leaveTheApb;
  count = 0;
  sum = 0;
  displayTheSpan = function(){
    $('.num').css('display', 'none');
  };
  clickToFetchANumber = function(){
    $('.button').click(buttonsEvent);
  };
  buttonsEvent = function(){
    var t, t2, buttonset, i$, len$, i, xhr;
    t = this.childNodes[0];
    t2 = this;
    buttonset = $('.button');
    if (!$(t.parentNode).hasClass('clicked') && !$(t.parentNode).hasClass('cannotclick')) {
      for (i$ = 0, len$ = buttonset.length; i$ < len$; ++i$) {
        i = buttonset[i$];
        if (i !== this) {
          $(i).css('background-color', 'rgba(0,0,20,.6)');
          $(i).addClass('cannotclick');
        }
      }
      t.style.display = 'inline';
      $(t.parentNode).addClass('clicked');
      xhr = new XMLHttpRequest();
      xhr.open("GET", "http://localhost:3000/", true);
      xhr.onreadystatechange = function(){
        var n, i$, ref$, len$, i;
        if (xhr.readyState == 4 && xhr.status == 200) {
          t.innerHTML = xhr.responseText;
          n = parseInt(xhr.responseText);
          t.parentNode.style.backgroundColor = 'rgba(0,0,20,.6)';
          if (!isNaN(n)) {
            sum = sum + n;
          }
          console.log(sum);
          count = count + 1;
          console.log(count);
          if (count == 5) {
            setBubbleColorToClick();
          }
          for (i$ = 0, len$ = (ref$ = buttonset).length; i$ < len$; ++i$) {
            i = ref$[i$];
            if (i !== t2 && !$(i).hasClass('clicked')) {
              $(i).css('background-color', 'rgba(48, 63, 159, 1)');
              $(i).removeClass('cannotclick');
            }
          }
        }
      };
      xhr.send(null);
    }
  };
  setBubbleColorToClick = function(){
    var bubble;
    bubble = $('.info');
    bubble.css('background-color', 'rgba(48, 63, 159, 1)');
    bubble.css('transition', 'all 0.6s');
  };
  clickToCalculateTheSum = function(){
    $('.info').click(calculateTheSum);
  };
  calculateTheSum = function(){
    if (count == 5) {
      $('.sum').html(sum);
      this.style.backgroundColor = 'rgba(0,0,20,.6)';
    }
  };
  mouseLeaveTheAtplus = function(){
    $('#at-plus-container').mouseleave(leaveTheApb);
  };
  leaveTheApb = function(){
    $('.num').html('...');
    $('.num').css('display', 'none');
    $('.button').removeClass('cannotclick');
    $('.button').removeClass('clicked');
    $('.button').css('background-color', 'rgba(48,63,159,1)');
    $('.info').css('background-color', 'rgba(0,0,20,.6)');
    $('.sum').html('');
    sum = 0;
    count = 0;
  };
  $(function(){
    displayTheSpan();
    clickToFetchANumber();
    clickToCalculateTheSum();
    mouseLeaveTheAtplus();
  });
}).call(this);
