// Generated by CoffeeScript 1.9.1
(function() {
  var A, B, C, D, E, RandomRobot, bubbleHandler, calculate, callback, callback_, change, color, disable, enable, getRandom, liList, reset, robot, setBubbleEnable, setLabel, showMessage;

  getRandom = function(e) {
    var tar;
    tar = e.target || window.target;
    if (!$(tar).find("span").get(0)) {
      tar = tar.parentNode;
    }
    if (!$(tar).find("[class=unread]").get(0)) {
      setLabel(tar);
      return $.get("/", callback);
    }
  };

  reset = function() {
    return 0;
  };

  A = function(tar, curremntSum) {
    if (!$(tar).find("[class=unread]").get(0)) {
      setLabel(tar);
      $.get("/", function(data) {
        return callback_(data, curremntSum, 0);
      });
      return disable();
    }
  };

  B = function(tar, curremntSum) {
    if (!$(tar).find("[class=unread]").get(0)) {
      setLabel(tar);
      $.get("/", function(data) {
        return callback_(data, curremntSum, 1);
      });
      return disable();
    }
  };

  C = function(tar, curremntSum) {
    if (!$(tar).find("[class=unread]").get(0)) {
      setLabel(tar);
      $.get("/", function(data) {
        return callback_(data, curremntSum, 2);
      });
      return disable();
    }
  };

  D = function(tar, curremntSum) {
    if (!$(tar).find("[class=unread]").get(0)) {
      setLabel(tar);
      $.get("/", function(data) {
        return callback_(data, curremntSum, 3);
      });
      return disable();
    }
  };

  E = function(tar, curremntSum) {
    if (!$(tar).find("[class=unread]").get(0)) {
      setLabel(tar);
      $.get("/", function(data) {
        return callback_(data, curremntSum, 4);
      });
      return disable();
    }
  };

  bubbleHandler = function(sum) {
    var tar;
    tar = $(".info-bar").get(0);
    return showMessage("楼主异步调用战斗力感人，目测不超过" + sum);
  };

  change = function(unread, data) {
    unread.innerHTML = data;
    return 0;
  };

  enable = function() {
    var i, len, li, liList;
    liList = $("#control-ring li");
    for (i = 0, len = liList.length; i < len; i++) {
      li = liList[i];
      if (!$(li).find("[class=unread]").get(0)) {
        color("rgba(61,40,166,1)", li);
      }
    }
    return 0;
  };

  calculate = function() {
    var add, i, len, ref, span, sum;
    sum = 0;
    add = function(span) {
      return sum = sum + parseInt(span.innerHTML);
    };
    ref = $("[class=unread] span");
    for (i = 0, len = ref.length; i < len; i++) {
      span = ref[i];
      add(span);
    }
    $(".info").css("background-color", "grey");
    $("#info-bar").unbind("click");
    return sum;
  };

  setBubbleEnable = function() {
    color("rgba(61,40,166,1)", ".info");
    return $("#info-bar").click(bubbleHandler);
  };

  callback = function(data, textStatus) {
    var UnreadList, i, len, unread;
    UnreadList = $("[class=unread] span");
    for (i = 0, len = UnreadList.length; i < len; i++) {
      unread = UnreadList[i];
      if (unread.innerHTML === "...") {
        change(unread, data);
      }
    }
    enable();
    if ($("li [class=unread]").length === 5) {
      setBubbleEnable();
      $("#control-ring").unbind("click");
    }
    return 0;
  };

  callback_ = function(data, curSum, tarNum) {
    var UnreadList, error, exception, i, len, unread;
    UnreadList = $("[class=unread] span");
    for (i = 0, len = UnreadList.length; i < len; i++) {
      unread = UnreadList[i];
      if (!(unread.innerHTML === "...")) {
        continue;
      }
      change(unread, data);
      curSum += parseInt(data);
      break;
    }
    enable();
    exception = Math.floor(Math.random() * 2);
    error = '';
    if (exception > 0) {
      error = "？不！";
    }
    switch (tarNum) {
      case 0:
        showMessage("这是个天大的秘密" + error);
        break;
      case 1:
        showMessage("我不知道" + error);
        break;
      case 2:
        showMessage("你不知道" + error);
        break;
      case 3:
        showMessage("他不知道" + error);
        break;
      case 4:
        showMessage("才怪" + error);
    }
    if ($("li [class=unread]").length === 5) {
      bubbleHandler(curSum);
    } else {
      robot($("li [class=unread]").length, curSum);
    }
    return 0;
  };

  color = function(colorName, li) {
    return $(li).css("background-color", "" + colorName);
  };

  disable = function() {
    var i, len, li, liList;
    liList = $("#control-ring li");
    for (i = 0, len = liList.length; i < len; i++) {
      li = liList[i];
      color("grey", li);
    }
    $("#control-ring").unbind("click");
    return 0;
  };

  setLabel = function(tar) {
    var unread;
    unread = $("<div class='unread'><span>...</span></div>");
    $(tar).append(unread.get(0));
    return 0;
  };

  showMessage = function(str) {
    var msg;
    msg = $("<span>" + str + "</span>");
    $("#msg").append(msg);
    return console.log(str);
  };

  robot = function(seq, curremntSum) {
    var curIndex, i, k, newList, tar;
    if (seq > 4) {
      return 0;
    }
    newList = $("#seqNum").html().split("");
    for (k = i = 0; i <= 4; k = ++i) {
      switch (newList[k]) {
        case "A":
          newList[k] = 0;
          break;
        case 'B':
          newList[k] = 1;
          break;
        case 'C':
          newList[k] = 2;
          break;
        case 'D':
          newList[k] = 3;
          break;
        case 'E':
          newList[k] = 4;
      }
    }
    curIndex = newList[seq];
    tar = $("#control-ring li").get(curIndex);
    switch (seq) {
      case 0:
        return A(tar, curremntSum);
      case 1:
        return B(tar, curremntSum);
      case 2:
        return C(tar, curremntSum);
      case 3:
        return D(tar, curremntSum);
      case 4:
        return E(tar, curremntSum);
    }
  };

  RandomRobot = function() {
    var cur, curSeq, i, item, k, len, newList, numList, str;
    numList = ["A", "B", "C", "D", "E"];
    str = "";
    newList = [];
    while (newList.length < 5) {
      cur = Math.floor(Math.random() * 5);
      k = true;
      for (i = 0, len = newList.length; i < len; i++) {
        item = newList[i];
        if (item === cur) {
          k = false;
        }
      }
      if (k) {
        newList.push(cur);
        str += numList[cur];
      }
    }
    curSeq = $("<span id='seqNum'>" + str + "</span>");
    $(".info").append(curSeq);
    $(".icon").unbind("click");
    return robot(0, 0);
  };

  $(".icon").click(RandomRobot);

  $(".icon").bind("onmouseover", "reset()");

  liList = $("#control-ring li");

  $(liList.get(0)).click(A);

  $(liList.get(1)).click(B);

  $(liList.get(2)).click(C);

  $(liList.get(3)).click(D);

  $(liList.get(4)).click(E);

}).call(this);
