// Generated by LiveScript 1.3.1
var getRandomNumber, getNumbers, activation;
$(function(){
  activation();
  getNumbers();
});
getRandomNumber = function(circle, flag){
  var buttons, lis, xmlHttpReg;
  buttons = document.getElementsByTagName("ul");
  lis = buttons[1].getElementsByTagName("li");
  xmlHttpReg = null;
  xmlHttpReg = new XMLHttpRequest();
  if (xmlHttpReg !== null) {
    xmlHttpReg.open("get", "/", true);
    xmlHttpReg.send();
    return xmlHttpReg.onreadystatechange = function(){
      var i$, i;
      if (xmlHttpReg.readyState === 4 && xmlHttpReg.status === 200) {
        circle.innerHTML = xmlHttpReg.responseText;
        for (i$ = 0; i$ <= 4; ++i$) {
          i = i$;
          flag[i] = 1;
          lis[i].style.backgroundColor = "#234991";
        }
      }
    };
  }
};
getNumbers = function(){
  var buttons, lis, ans, flag, isclicked, i$, i;
  buttons = document.getElementsByTagName("ul");
  lis = buttons[1].getElementsByTagName("li");
  ans = buttons[0].getElementsByTagName("li")[0];
  flag = [];
  isclicked = [];
  for (i$ = 0; i$ <= 4; ++i$) {
    i = i$;
    lis[i].style.backgroundColor = "#234991";
    flag[i] = 1;
    isclicked[i] = 0;
  }
  for (i$ = 0; i$ <= 4; ++i$) {
    (fn$.call(this, i$));
  }
  ans.onclick = function(){
    var sum, cansum, numbers, i$, i, tbuttons, tlis, tsp;
    sum = 0;
    cansum = 1;
    numbers = [];
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      if (isclicked[i] === 0) {
        cansum = 0;
      }
    }
    if (cansum) {
      tbuttons = document.getElementsByTagName("ul");
      tlis = buttons[1].getElementsByTagName("li");
      tsp = [];
      this.style.backgroundColor = "#234991";
      for (i$ = 0; i$ <= 4; ++i$) {
        i = i$;
        tsp[i] = parseInt(tlis[i].getElementsByTagName("span")[0].innerHTML);
        sum += tsp[i];
      }
      buttons[0].getElementsByTagName("li")[0].getElementsByTagName("span")[0].innerHTML = sum;
      for (i$ = 0; i$ <= 4; ++i$) {
        i = i$;
        isclicked[i] = 0;
      }
    }
  };
  function fn$(i){
    lis[i].onclick = function(){
      var i$, j, circle;
      isclicked[i] = 1;
      if (flag[i]) {
        for (i$ = 0; i$ <= 4; ++i$) {
          j = i$;
          if (j !== i) {
            flag[j] = 0;
            lis[j].style.backgroundColor = "#7E7E7E";
          }
        }
        circle = this.getElementsByTagName("span")[0];
        circle.style.display = "inline";
        circle.innerHTML = "...";
        getRandomNumber(circle, flag);
      }
    };
  }
};
activation = function(){
  var buttons, area;
  buttons = document.getElementById("button");
  buttons.onmouseover = function(){
    document.getElementById("area").className = "at-plus-container-block";
    this.id = "button_hover";
  };
  area = document.getElementById("area");
  area.onmouseleave = function(){
    location.reload();
  };
  return area = document.getElementById("area");
};