// Generated by CoffeeScript 1.9.0
(function() {
  var diable_other_button, enable_other_button, get_sum, resert_all, show_button;

  $(function() {
    $('.button').click(function() {
      return diable_other_button(this);
    });
    return $("#bottom-positioner").mouseenter(function() {
      return resert_all();
    });
  });

  diable_other_button = function(button) {
    var buttons, i, _i, _len;
    if ($(button).attr("clicked") === "true") {
      return;
    }
    buttons = $(button).siblings("li");
    for (_i = 0, _len = buttons.length; _i < _len; _i++) {
      i = buttons[_i];
      $(i).attr("clicked", "true");
      $(i).css({
        "background-color": "grey"
      });
    }
    return show_button(button);
  };

  show_button = function(button) {
    console.log($(button));
    $(button).children(".unread").css({
      "visibility": "visible"
    });
    return $.ajax('/', {
      type: 'GET',
      dataType: 'html',
      error: function(jqXHR, textStatus, errorThrown) {
        return console.log("ajax wrong");
      },
      success: function(data, textStatus, jqXHR) {
        $(button).children(".unread").html("" + data);
        $(button).css({
          "background-color": "grey"
        });
        return enable_other_button(button);
      }
    });
  };

  enable_other_button = function(button) {
    var buttons, i, _i, _len;
    buttons = $(button).siblings("li");
    for (_i = 0, _len = buttons.length; _i < _len; _i++) {
      i = buttons[_i];
      if ($(i).children(".unread").html() === "...") {
        $(i).css({
          "background-color": "rgba(48,63,159,1)"
        });
        $(i).attr("clicked", "false");
      }
    }
    $(button).attr("clicked", "true");
    return get_sum(button);
  };

  get_sum = function(button) {
    var buttons, count, i, sum, _i, _len;
    sum = 0;
    count = 1;
    buttons = $(button).siblings("li");
    sum += parseInt($(button).children(".unread").html());
    for (_i = 0, _len = buttons.length; _i < _len; _i++) {
      i = buttons[_i];
      if ($(i).children(".unread").html() !== "...") {
        sum += parseInt($(i).children(".unread").html());
        count++;
      }
    }
    if (count === 5) {
      $("#info-bar").css({
        "background-color": "rgba(48,63,159,1)"
      });
      return $("#info-bar").click(function() {
        $(".sum").text(sum);
        return $("#info-bar").css({
          "background-color": "grey"
        });
      });
    }
  };

  resert_all = function() {
    var buttons, i, _i, _len, _results;
    buttons = $(".button");
    $(".sum").text("");
    _results = [];
    for (_i = 0, _len = buttons.length; _i < _len; _i++) {
      i = buttons[_i];
      $(i).attr("clicked", "false");
      $(i).children(".unread").html("...");
      $(i).children(".unread").css({
        "visibility": "hidden"
      });
      _results.push($(i).css({
        "background-color": "rgba(48,63,159,1)"
      }));
    }
    return _results;
  };

}).call(this);
