// Generated by LiveScript 1.3.1
(function(){
  var clickOnAButton, displayTheRedBadge, disableAllOtherButtons, getNumberFromTheServer, enableOtherButtons, clickOnTheBubble, initialAtplus;
  $(function(){
    var buttons, bubble;
    buttons = $('#control-ring li');
    bubble = $('#info-bar');
    buttons.click(function(){
      clickOnAButton(this);
    });
    return bubble.click(function(){
      clickOnTheBubble(bubble);
    });
  });
  clickOnAButton = function(theButton){
    var disable;
    disable = $(theButton).attr("state");
    if (disable !== "disable" && disable !== "clicked") {
      displayTheRedBadge(theButton);
      disableAllOtherButtons(theButton);
      getNumberFromTheServer(theButton);
      $(theButton).attr("state", "clicked");
    }
  };
  displayTheRedBadge = function(theButton){
    var badge;
    badge = $(theButton).children('.unread');
    badge.css('display', 'block').html('...');
  };
  disableAllOtherButtons = function(theButton){
    var buttons, i$, len$, button, clicked;
    buttons = $('#control-ring li');
    for (i$ = 0, len$ = buttons.length; i$ < len$; ++i$) {
      button = buttons[i$];
      if (button !== theButton) {
        clicked = $(button).attr("state");
        if (clicked !== "clicked") {
          $(button).attr("state", "disable");
          $(button).css("background-color", "#7E7E7E");
        }
      }
    }
  };
  getNumberFromTheServer = function(theButton){
    return $.get('/', function(data){
      $(theButton).children('.unread').html(data);
      enableOtherButtons(theButton);
      $(theButton).css("background-color", "#7E7E7E");
    });
  };
  enableOtherButtons = function(theButton){
    var buttons, i$, len$, button, clicked;
    buttons = $('#control-ring li');
    for (i$ = 0, len$ = buttons.length; i$ < len$; ++i$) {
      button = buttons[i$];
      if (button !== theButton) {
        clicked = $(button).attr("state");
        if (clicked !== "clicked") {
          $(button).attr("state", "");
          $(button).css("background-color", "#192E89");
        }
      }
    }
  };
  clickOnTheBubble = function(bubble){
    var sumArea, sum, i$, ref$, len$, button;
    sumArea = $('sum');
    sum = 0;
    for (i$ = 0, len$ = (ref$ = buttons).length; i$ < len$; ++i$) {
      button = ref$[i$];
      if ($(button).html === "" || $(button).html === "...") {
        return;
      }
      sum += parseInt($(button).children('.unread').html());
    }
    sumArea.html = sum;
  };
  initialAtplus = function(){
    if (this.mouseOutofAtplus()) {
      this.resetEverything();
    }
  };
}).call(this);
