// Generated by LiveScript 1.3.1
(function(){
  var getnumber, enable_other_button, disable_other_button, show_number, all_button_done, button_click, add_button_click, add_info_click, reset_number, reset_buttons, reset_info, reset;
  getnumber = function(this_id){
    var request;
    request = new XMLHttpRequest();
    request.onreadystatechange = function(){
      if (request.readyState === 4 && request.status === 200) {
        $("#" + this_id)[0].innerHTML = request.responseText;
        enable_other_button(this_id);
        if (all_button_done()) {
          return add_info_click();
        }
      }
    };
    request.open("GET", "/" + this_id, true);
    return request.send();
  };
  enable_other_button = function(this_id){
    var lis, number, i$, i, results$ = [];
    lis = $(".plank");
    number = $(".number");
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      if (number[i].classList.contains("appear")) {
        results$.push(lis[i].style.backgroundColor = 'gray');
      } else {
        results$.push(lis[i].style.backgroundColor = 'rgba(48,63,159,.8)');
      }
    }
    return results$;
  };
  disable_other_button = function(this_id){
    var lis, i$, i, results$ = [];
    lis = $(".plank");
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      if (i !== this_id) {
        results$.push(lis[i].style.backgroundColor = 'gray');
      }
    }
    return results$;
  };
  show_number = function(this_id){
    var number;
    number = $(".number");
    number[this_id].classList.remove("disappear");
    return number[this_id].classList.add("appear");
  };
  all_button_done = function(){
    var number, i$, i;
    number = $(".number");
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      if (number[i].innerHTML === "...") {
        return false;
      }
    }
    return true;
  };
  button_click = function(this_id){
    var buttons, number, lis;
    buttons = $(".letter");
    number = $(".number");
    lis = $(".plank");
    if (number[this_id].style.display === "block") {
      return;
    }
    if (lis[this_id].style.backgroundColor === "gray") {
      return;
    }
    show_number(this_id);
    disable_other_button(this_id);
    return getnumber(this_id);
  };
  add_button_click = function(){
    var buttons, i$, i, results$ = [];
    buttons = $(".letter");
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      buttons[i].Index = i;
      results$.push(buttons[i].onclick = fn$);
    }
    return results$;
    function fn$(){
      return button_click(this.Index);
    }
  };
  add_info_click = function(){
    var buttons;
    buttons = $(".letter");
    return $('#info-bar')[0].onclick = function(){
      var number, k, i$, i;
      if (all_button_done() !== true) {
        return;
      }
      number = $(".number");
      k = 0;
      for (i$ = 0; i$ <= 4; ++i$) {
        i = i$;
        k += parseInt(number[i].innerHTML);
      }
      return $('#big')[0].innerHTML = k;
    };
  };
  reset_number = function(){
    var number, i$, i, results$ = [];
    number = $('.number');
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      number[i].innerHTML = '...';
      number[i].classList.add("disappear");
      results$.push(number[i].classList.remove("appear"));
    }
    return results$;
  };
  reset_buttons = function(){
    enable_other_button(-1);
    return reset_number();
  };
  reset_info = function(){
    return $('#big')[0].innerHTML = "";
  };
  reset = function(){
    reset_buttons();
    return reset_info();
  };
  window.onload = function(){
    reset();
    add_button_click();
    add_info_click();
    return $('#at-plus-container')[0].onmouseleave = reset;
  };
}).call(this);
