// Generated by LiveScript 1.3.1
(function(){
  var getNumber, enableOtherButton, disableOtherButton, showNumber, allButtonDone, buttonClick, addButtonClick, addInfoClick, resetNumber, resetButtons, resetInfo, reset, robot, robotAction;
  getNumber = function(this_id, callback){
    var request;
    if (window.XMLHttpRequest) {
      request = new XMLHttpRequest();
    } else {
      request = new ActiveXObject('Microsoft.XMLHTTP');
    }
    request.open("GET", "/" + this_id, true);
    request.onreadystatechange = function(){
      if (request.readyState === 4 && request.status === 200) {
        $("#" + this_id)[0].innerHTML = request.responseText;
        enableOtherButton(this_id);
        if (allButtonDone()) {
          addInfoClick();
        }
        if (typeof callback == 'function') {
          callback();
        }
      }
    };
    request.send();
  };
  enableOtherButton = function(this_id){
    var lis, number, i$, i, results$ = [];
    lis = $('.plank');
    number = $('.number');
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      if (number[i].classList.contains('appear')) {
        results$.push(lis[i].style.backgroundColor = 'gray');
      } else {
        results$.push(lis[i].style.backgroundColor = 'rgba(48,63,159,.8)');
      }
    }
    return results$;
  };
  disableOtherButton = function(this_id){
    var lis, i$, i, results$ = [];
    lis = $('.plank');
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      if (i !== this_id) {
        results$.push(lis[i].style.backgroundColor = 'gray');
      }
    }
    return results$;
  };
  showNumber = function(this_id){
    var number;
    number = $('.number');
    number[this_id].classList.remove('disappear');
    return number[this_id].classList.add('appear');
  };
  allButtonDone = function(){
    var number, i$, i;
    number = $('.number');
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      if (number[i].innerHTML === '...') {
        return false;
      }
    }
    return true;
  };
  buttonClick = function(this_id){
    var buttons, number, lis;
    buttons = $('.letter');
    number = $('.number');
    lis = $('.plank');
    if (number[this_id].style.display === 'block') {
      return;
    }
    showNumber(this_id);
    disableOtherButton(this_id);
    getNumber(this_id, buttons[this_id].callback);
  };
  addButtonClick = function(){
    var buttons, i$, i, results$ = [];
    buttons = $('.letter');
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      buttons[i].Index = i;
      results$.push(buttons[i].onclick = fn$);
    }
    return results$;
    function fn$(){
      return buttonClick(this.Index);
    }
  };
  addInfoClick = function(){
    var buttons;
    buttons = $('.letter');
    $('#info-bar')[0].onclick = function(){
      var number, k, i$, i;
      if (allButtonDone() !== true) {
        return;
      }
      number = $('.number');
      k = 0;
      for (i$ = 0; i$ <= 4; ++i$) {
        i = i$;
        k += parseInt(number[i].innerHTML);
      }
      $('#big')[0].innerHTML = k;
    };
  };
  resetNumber = function(){
    var number, i$, i, results$ = [];
    number = $('.number');
    for (i$ = 0; i$ <= 4; ++i$) {
      i = i$;
      number[i].innerHTML = '...';
      number[i].classList.add('disappear');
      results$.push(number[i].classList.remove('appear'));
    }
    return results$;
  };
  resetButtons = function(){
    enableOtherButton(-1);
    return resetNumber();
  };
  resetInfo = function(){
    return $('#big')[0].innerHTML = "";
  };
  reset = function(){
    resetButtons();
    resetInfo();
    return $('.apb')[0].state = 'enable';
  };
  robot = function(){
    $('.apb')[0].onclick = function(){
      robotAction();
    };
  };
  robotAction = function(){
    var buttons, i$;
    buttons = $('.letter');
    for (i$ = 0; i$ <= 4; ++i$) {
      (fn$.call(this, i$));
    }
    function fn$(i){
      buttons[i].callback = function(){
        $('#info-bar')[0].click();
      };
      buttons[i].click();
    }
  };
  window.onload = function(){
    reset();
    robot();
    addButtonClick();
    addInfoClick();
    $('#at-plus-container')[0].onmouseleave = reset;
  };
}).call(this);
