// Generated by LiveScript 1.3.1
(function(){
  var aHandler, bHandler, cHandler, dHandler, eHandler, bubbleHandler, addResettingWhenLeaveApb, disableOtherButtons, enableOtherButtons, system, robot, robotGenerateARandomOrderAndThenClick;
  $(function(){
    system.initial();
    robot.initial();
    addResettingWhenLeaveApb();
    robotGenerateARandomOrderAndThenClick();
  });
  aHandler = function(next){
    var thisButton;
    if (!system.buttons_request["A"] && system.getRequestLock()) {
      thisButton = $('#A_btn');
      thisButton.find('.unread').addClass("show").text("...");
      disableOtherButtons($('#A_btn'));
      system.buttons_request["A"] = $.get('http://localhost:3000/S4/', function(number, result){
        var sucess;
        thisButton.find('.unread').text(number);
        system.sum += parseInt(number);
        enableOtherButtons();
        system.releaseRequestLock();
        sucess = Math.random() > 0.3;
        if (!sucess) {
          console.log('A Faild!');
          return ['这不是个天大的秘密', system.sum];
        } else {
          $('#say').text('这是个天大的秘密');
        }
        if (typeof next == 'function') {
          next();
        }
      });
    }
  };
  bHandler = function(next){
    var thisButton;
    if (!system.buttons_request["B"] && system.getRequestLock()) {
      thisButton = $('#B_btn');
      thisButton.find('.unread').addClass("show").text("...");
      disableOtherButtons($('#A_btn'));
      system.buttons_request["B"] = $.get('http://localhost:3000/S4/', function(number, result){
        var sucess;
        thisButton.find('.unread').text(number);
        system.sum += parseInt(number);
        enableOtherButtons();
        system.releaseRequestLock();
        sucess = Math.random() > 0.3;
        if (!sucess) {
          console.log('B Faild!');
          return ['我知道', system.sum];
        } else {
          $('#say').text('我不知道');
        }
        if (typeof next == 'function') {
          next();
        }
      });
    }
  };
  cHandler = function(next){
    var thisButton;
    if (!system.buttons_request["C"] && system.getRequestLock()) {
      thisButton = $('#C_btn');
      thisButton.find('.unread').addClass("show").text("...");
      disableOtherButtons($('#A_btn'));
      system.buttons_request["C"] = $.get('http://localhost:3000/S4/', function(number, result){
        var sucess;
        thisButton.find('.unread').text(number);
        system.sum += parseInt(number);
        enableOtherButtons();
        system.releaseRequestLock();
        sucess = Math.random() > 0.3;
        if (!sucess) {
          console.log('C Faild!');
          return ['你知道', system.sum];
        } else {
          $('#say').text('你不知道');
        }
        if (typeof next == 'function') {
          next();
        }
      });
    }
  };
  dHandler = function(next){
    var thisButton;
    if (!system.buttons_request["D"] && system.getRequestLock()) {
      thisButton = $('#D_btn');
      thisButton.find('.unread').addClass("show").text("...");
      disableOtherButtons($('#A_btn'));
      system.buttons_request["D"] = $.get('http://localhost:3000/S4/', function(number, result){
        var sucess;
        thisButton.find('.unread').text(number);
        system.sum += parseInt(number);
        enableOtherButtons();
        system.releaseRequestLock();
        sucess = Math.random() > 0.3;
        if (!sucess) {
          console.log('D Faild!');
          return ['他知道', system.sum];
        } else {
          $('#say').text('他不知道');
        }
        if (typeof next == 'function') {
          next();
        }
      });
    }
  };
  eHandler = function(next){
    var thisButton;
    if (!system.buttons_request["E"] && system.getRequestLock()) {
      thisButton = $('#E_btn');
      thisButton.find('.unread').addClass("show").text("...");
      disableOtherButtons($('#A_btn'));
      system.buttons_request["E"] = $.get('http://localhost:3000/S4/', function(number, result){
        var sucess;
        thisButton.find('.unread').text(number);
        system.sum += parseInt(number);
        enableOtherButtons();
        system.releaseRequestLock();
        sucess = Math.random() > 0.3;
        if (!sucess) {
          console.log('E Faild!');
          return ['才怪', system.sum];
        } else {
          $('#say').text('才怪');
        }
        if (typeof next == 'function') {
          next();
        }
      });
    }
  };
  bubbleHandler = function(){
    if ($('#info-bar').hasClass("enable")) {
      $('#info-bar').find('.sum').text(system.sum);
      $('#say').text("楼主异步调用战斗力感人，目测不超过" + system.sum);
      $('#info-bar').removeClass("enable").addClass("disable");
    }
  };
  addResettingWhenLeaveApb = function(){
    $('#button').mouseleave(function(){
      system.reset();
    });
  };
  disableOtherButtons = function(thisButton){
    var i$, ref$, len$;
    for (i$ = 0, len$ = (ref$ = $('#control-ring .button')).length; i$ < len$; ++i$) {
      (fn$.call(this, i$, ref$[i$]));
    }
    function fn$(i, dom){
      if ($(dom).attr("title") !== thisButton.attr("title")) {
        $(dom).removeClass('enable').addClass('disable');
      }
    }
  };
  enableOtherButtons = function(){
    var i$, ref$, len$;
    for (i$ = 0, len$ = (ref$ = $('#control-ring .button')).length; i$ < len$; ++i$) {
      (fn$.call(this, i$, ref$[i$]));
    }
    if (system.allButtonHasFetchedNumber()) {
      $('#info-bar').removeClass("disable").addClass("enable");
    }
    function fn$(i, dom){
      if (!system.buttons_request[$(dom).attr("title")]) {
        $(dom).removeClass('disable').addClass('enable');
      } else {
        $(dom).removeClass('enable').addClass('disable');
      }
    }
  };
  system = {
    initial: function(){
      this.buttons_request = [];
      this.sum = 0;
      this.request_command = false;
    },
    getRequestLock: function(){
      if (this.request_command === false) {
        return this.request_command = true;
      } else {
        return false;
      }
    },
    releaseRequestLock: function(){
      this.request_command = false;
    },
    allButtonHasFetchedNumber: function(){
      var i$, ref$, len$, i;
      for (i$ = 0, len$ = (ref$ = ["A", "B", "C", "D", "E"]).length; i$ < len$; ++i$) {
        i = ref$[i$];
        if (!this.buttons_request[i]) {
          return false;
        }
      }
      return true;
    },
    reset: function(){
      var i$, ref$, len$, i;
      for (i$ = 0, len$ = (ref$ = ["A", "B", "C", "D", "E"]).length; i$ < len$; ++i$) {
        i = ref$[i$];
        if (this.buttons_request[i] && this.buttons_request[i].readyState !== 4) {
          this.buttons_request[i].abort();
        }
        this.buttons_request[i] = undefined;
      }
      for (i$ = 0, len$ = (ref$ = $('#control-ring .button')).length; i$ < len$; ++i$) {
        (fn$.call(this, i$, ref$[i$]));
      }
      $('#info-bar').removeClass("enable").addClass('disable');
      $('#info-bar').find('.sum').text("");
      $('#info-bar').find('.random_sort').text("");
      this.sum = 0;
      this.request_command = false;
      $('#say').text("");
      robot.initial();
      function fn$(i, dom){
        $(dom).find('.unread').removeClass("show").addClass("unshow");
        $(dom).removeClass('disable').addClass('enable');
      }
    }
  };
  robot = {
    initial: function(){
      this.bubble = $('#info-bar');
      this.sequence = ["A", "B", "C", "D", "E"];
      this.cursor = 0;
      this.handlers = [aHandler, bHandler, cHandler, dHandler, eHandler];
    },
    shuffleOrder: function(){
      this.sequence.sort(function(){
        return 0.5 - Math.random();
      });
    },
    clickNext: function(){
      if (this.cursor === this.sequence.length) {
        bubbleHandler();
      } else {
        this.getNextHandler()(function(){
          robot.clickNext();
        });
      }
    },
    getNextHandler: function(){
      var index;
      index = this.sequence[this.cursor++].charCodeAt() - 'A'.charCodeAt();
      return this.handlers[index];
    },
    showOrder: function(){
      this.bubble.find('.random_sort').text(this.sequence.join(', '));
    }
  };
  robotGenerateARandomOrderAndThenClick = function(){
    $('#button .apb').click(function(){
      robot.shuffleOrder();
      robot.showOrder();
      robot.clickNext();
    });
  };
}).call(this);
